<?php
$escHtml = $this->plugin('escapeHtml');
$escAttr = $this->plugin('escapeHtmlAttr');

$banner = $this->themeSettingAsset('banner');
$bannerWidth = $this->themeSetting('banner_width') ?? '';
$bannerHeight = $this->themeSetting('banner_height') ?? '';
$bannerVerticalPosition = ($this->themeSetting('banner_v_position')) ?? 'center';
$bannerHorizontalPosition = ($this->themeSetting('banner_h_position')) ?? 'center';

$bannerHeading = $this->themeSetting('banner_heading');
$bannerDescription = $this->themeSetting('banner_description');
$bannerContentPosition = $this->themeSetting('banner_content_position') ?? 'left';

$bannerHeightProperty = $bannerHeading || $bannerDescription ? 'min-height' : 'height';

$bannerInlineStyles = '';
$imageInlineStyles = '';

if ($bannerHeight) {
    $bannerInlineStyles .= "{$bannerHeightProperty}: {$bannerHeight};";
} else {
    $bannerInlineStyles .= "{$bannerHeightProperty}: 20vh;";
}

$imageInlineStyles .= "object-position: {$bannerHorizontalPosition} {$bannerVerticalPosition};";

$class = ['banner'];
$class[] = $bannerWidth;
if ($bannerHeading || $bannerDescription) {
    $class[] = 'has-text';
}
?>

<?php if ($banner) : ?>
    <div class="<?php echo implode(' ', $class); ?>" style="<?php echo $escAttr($bannerInlineStyles); ?>">

        <?php echo $this->thumbnail($banner, 'large', ['style' => $imageInlineStyles, 'role' => 'presentation', 'aria-hidden' => 'true']); ?>

        <div class="banner__content banner__content--<?php echo $bannerContentPosition; ?>">
            <?php if($bannerHeading) : ?>
                <h2 class="banner__heading"><?php echo $escHtml($bannerHeading); ?></h2>
            <?php endif; ?>
            <?php if($bannerDescription) : ?>
                <p class="banner__description"><?php echo $escHtml($bannerDescription); ?></p>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
