<?php
$navDepth = (int) $this->themeSetting('nav_depth') ? (int) $this->themeSetting('nav_depth') -1 : -1;
?>

<header class="main-header">

	<?php echo $userBar; ?>

	<?php echo $this->partial('common/top-header'); ?>

	<div class="main-header__main-bar container">
		<h1 class="main-header__site-title site-title">
			<a href="<?php echo $site->url(); ?>">
			<?php if ($this->themeSetting('logo')): ?>
				<img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $this->escapeHtml( $site->title() ); ?>" />
			<?php else: ?>
				<?php echo $this->escapeHtml( $site->title() ); ?>
			<?php endif; ?>
			</a>
		</h1>

		<?php echo $this->partial('common/main-header-search', array('class' => 'd-block d-xl-none', 'site' => $site)); ?>

		<nav class="main-navigation">
			<div class="main-navigation__container">
				<?php
				echo $site->publicNav()->menu()->renderMenu(null, [
					'addClassToListItem' => true,
					'maxDepth' => $navDepth
				]);
				?>
			</div>
			<button
				 class="main-navigation__toggle"
				 aria-expanded="false"
				 aria-controls="menu-drawer"
			>
				<span class="sr-only">Open menu</span>
				<span aria-hidden="true"></span>
				<span aria-hidden="true"></span>
				<span aria-hidden="true"></span>
			</button>
		</nav>

		<?php echo $this->partial('common/menu-drawer'); ?>

		<?php echo $this->partial('common/main-header-search', array('class' => 'd-none d-xl-block', 'site' => $site)); ?>

	</div>

</header>
