<nav id="menu-drawer" class="menu-drawer" style="display: none;">
	<div class="wrap">

		<div class="navigation-controls">
			<a href="."
				id="menu-backer"
				class="menu-backer is-empty"
				title="<?php $this->translate( 'Close Menu' ); ?>"
			>
				<?php $this->translate( 'Close Menu' ); ?>
			</a>
		</div><!-- .navigation-controls -->

		<div id="menu-clones" class="menu-container">

			<?php
			// menus placed here via Javascript (see: asset/js/navigation.js)
			?>

		</div><!-- .menu-container -->

	</div><!-- .wrap -->
</nav><!-- menu-drawer -->
