<?php
    $contactInfoPosition = $this->themeSetting('contact_info_position');
    $contactInfoPhone = $this->themeSetting('contact_info_phone') ?? '';
    $contactInfoEmail = $this->themeSetting('contact_info_email') ?? '';
    $contactInfoLocation = $this->themeSetting('contact_info_location') ?? '';
    $contactInfoLocationLink = $this->themeSetting('contact_info_location_link') ?? '';
?>

<div class="main-header__top-bar">
    <div class="container">
        <?php if (is_array($contactInfoPosition) && in_array('top_header', $contactInfoPosition)) : ?>
            <div class="top-bar__info">
                <?php if ($contactInfoLocation) : ?>
                    <?php if ($contactInfoLocationLink) : ?>
                        <a class="contact_info contact_info_location" target="_blank" href="<?php echo $contactInfoLocationLink; ?>">
                    <?php else : ?>
                        <div class="contact_info contact_info_location">
                    <?php endif; ?>
                            <?php echo $contactInfoLocation; ?>
	                <?php if ($contactInfoLocationLink) : ?>
                        </a>
	                <?php else : ?>
                        </div>
		            <?php endif; ?>
                <?php endif; ?>
                <?php if ($contactInfoPhone) : ?>
                    <div class="contact_info contact_info_phone"><a href="tel:<?php echo $contactInfoPhone; ?>"><?php echo $contactInfoPhone; ?></a></div>
                <?php endif; ?>
                <?php if ($contactInfoEmail) : ?>
                    <div class="contact_info contact_info_email"><a target="_blank" href="mailto:<?php echo $contactInfoEmail; ?>"><?php echo $contactInfoEmail; ?></a></div>
                <?php endif; ?>
            </div>
        <?php endif; ?>

        <a class="top-bar__advanced-search" href="<?php echo $site->url() . '/item/search'; ?>">Advanced Search</a>

    </div>
</div>

