<?php
$translate = $this->plugin('translate');
$this->inlineScript()->appendFile($this->assetUrl('js/advanced-search.js'));
$this->htmlElement('body')->appendAttribute('class', 'items search');
?>

<h2><?php echo $translate('Advanced item search'); ?></h2>
<form id="advanced-search" method="get" action="<?php echo $this->escapeHtml($this->url(null, ['action' => 'browse'], true)); ?>">
<?php echo $this->partial(
    'common/advanced-search',
    ['query' => $this->params()->fromQuery(), 'resourceType' => 'item']
); ?>
<div id="page-actions">
    <input type="submit" name="submit" value="<?php echo $this->escapeHtml($translate('Search')); ?>">
    <input type="reset" value="<?php echo $this->escapeHtml($translate('Reset')); ?>" name="reset" class="reset-button btn--secondary" />
</div>
</form>
