<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->inlineScript()->appendFile($this->assetUrl('js/masonry.pkgd.min.js'));
$this->inlineScript()->appendFile($this->assetUrl('js/browse.js'));
$this->htmlElement('body')->appendAttribute('class', 'media resource browse');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;

$layoutSetting = $this->themeSetting('browse_layout', 'grid');
$gridState = ($layoutSetting == 'togglegrid') ? 'disabled' : '';
$listState = ($layoutSetting == 'togglelist') ? 'disabled': '';
$isGrid = (strpos($layoutSetting, 'grid') !== false) ? true : false;
$bodyTerm = $this->siteSetting('browse_body_property_term');
$bodyTruncate = $this->themeSetting('truncate_body_property');

if (isset($_GET['view'])) {
	if ('list' === $_GET['view']) {
		$gridState = '';
		$listState = 'disabled';
		$isGrid = false;
	} else {
		$gridState = 'disabled';
		$listState = '';
		$isGrid = true;
	}
}

$decoration = $this->themeSetting('image_decoration');
$decorationClass = '';

if (is_array($decoration) && in_array('media', $decoration)) {
    $decorationClass = $isGrid ? 'decoration' : 'decoration decoration--thumbnail';
}
?>

<?php echo $this->pageTitle($translate('Media'), 2); ?>

<?php echo $this->searchFilters(); ?>

<?php echo $this->pagination(); ?>

<div class="browse-controls">
    <?php if (strpos($layoutSetting, 'toggle') !== false): ?>
        <div class="layout-toggle">
            <button type="button" aria-label="<?php echo $translate('Grid'); ?>" class="grid icon-btn o-icon-grid" <?php echo $gridState; ?>></button>
            <button type="button" aria-label="<?php echo $translate('List'); ?>" class="list icon-btn o-icon-list" <?php echo $listState; ?>></button>
        </div>
    <?php endif; ?>
    <?php echo $this->browse()->renderSortSelector('medias'); ?>
    <div class="advanced-search-container">
        <?php echo $this->hyperlink($translate('Advanced search'), $this->url(null, ['action' => 'search'], true), ['class' => 'advanced-search']); ?>
    </div>
</div>

<?php $this->trigger('view.browse.before'); ?>

<div class="resources <?php echo ($isGrid) ? 'resource-grid' : 'resource-list'; ?>">
    <div class="grid-sizer"></div>
    <div class="gutter-sizer"></div>
    <?php
    foreach ($medias as $media):
        $body = $bodyTerm ? $media->value($bodyTerm, ['lang' => ($valueLang)]) : $media->displayDescription(null, ($valueLang));
        $primaryMedia = $media->primaryMedia();
        ?>
        <div class="item-set resource <?php echo ($isGrid) ? '' : 'media-object'; ?>">
            <!-- Thumbnail -->
            <?php if ($primaryMedia): ?>
                <div class="resource__thumbnail <?php echo $decorationClass; ?>">
                    <?php echo $media->linkRaw($this->thumbnail($primaryMedia, 'large')); ?>
                </div>
            <?php endif; ?>

            <!-- Content -->
            <div class="resource__content">
                <?php echo $this->ResourceTags($media); ?>
                <!-- Metadata -->
                <div class="resource__meta <?php echo ($isGrid) ? '' : 'media-object-section'; ?>">
                    <?php echo $media->link($media->displayTitle(null, $valueLang)); ?>
                    <?php if ($body): ?>
                        <div class="description <?php echo ($bodyTruncate) ? $bodyTruncate : ''; ?>"><?php echo $escape($body); ?></div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>

</div>

<?php $this->trigger('view.browse.after'); ?>

<?php echo $this->pagination(); ?>
