<?php
$decoration = $this->themeSetting('image_decoration');
$classes    = $classes ?? [];
if (isset($alignmentClass)) {
    $classes[] = $alignmentClass;
    $classes[] = 'file';
}
?>

<div class="<?php echo $this->escapeHtml(implode(' ', $classes)); ?>">
    <?php foreach($attachments as $attachment): ?>
        <?php $item = $attachment->item(); ?>
        <div class="item resource <?php echo is_array($decoration) && in_array('media', $decoration) ? 'decoration' : ''; ?>">
            <?php
            $media = $attachment->media() ?: $item->primaryMedia();
            if ($media):
                echo $media->render([
                    'thumbnailType' => $thumbnailType,
                    'link' => $link,
                ]);
            endif;
            ?>
            <?php if ($showTitleOption === 'item_title'): ?>
                <h3><?php echo $item->link($item->displayTitle()); ?></h3>
            <?php elseif ($showTitleOption === 'file_name'): ?>
                <h3><?php echo $media->displayTitle(); ?></h3>
            <?php endif; ?>
            <?php $caption = $attachment->caption(); ?>
            <?php if ($caption): ?>
                <div class="caption"><?php echo $caption; ?></div>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>
