<?php

$translate = $this->plugin('translate');
$showLocale = (bool) $this->siteSetting('show_locale_label', true);
$decoration = $this->themeSetting('image_decoration');
?>
<div class="item-with-metadata">
    <?php foreach($attachments as $attachment): ?>
        <?php
            $item = $attachment->item();
            $primaryMedia = $item->primaryMedia();
        ?>
        <?php if (empty($item)) continue; ?>
        <?php
        $options = [];
        if ($this->siteSetting('exclude_resources_not_in_site')) {
            $options['siteId'] = $this->currentSite()->id();
        }

        // Get title and title lang.
        $title = $item->displayTitle();

        if ($showLocale) {
            $template = $item->resourceTemplate();
            if ($template && $template->titleProperty()) {
                $titleTerm = $template->titleProperty()->term();
            } else {
                $titleTerm = 'dcterms:title';
            }
            $titleObj = $item->value($titleTerm);
            $titleLang = (string) $titleObj->lang();

            if ($titleLang) {
                $title .= '<span class="language">' . $titleLang . '</span>';
            }
        }
        ?>

        <div class="item-with-metadata__container">
            <!-- Header -->
            <div class="item-with-metadata__header">
                <?php echo $this->ResourceTags($item); ?>
                <h3 class="item-with-metadata__heading"><?php echo $title; ?></h3>
            </div>

            <!-- Content -->
            <div class="item-with-metadata__content">

                <!-- Thumbnail -->
                <?php if ($primaryMedia): ?>
                    <div class="item-with-metadata__thumbnail <?php echo is_array($decoration) && in_array('media', $decoration) ? 'decoration' : ''; ?>">
                        <?php echo $this->thumbnail($primaryMedia, 'large', ['class' => 'item-thumbnail']); ?>
                    </div>
                <?php endif; ?>

                <!-- Metadata -->
                <div class="metadata">
                    <?php echo $item->displayValues($options); ?>
                    <?php if($item->itemSets()): ?>
                        <dl class="item-sets">
                            <div class="property">
                                <dt><?php echo $translate('Item sets'); ?></dt>
                                <?php foreach ($item->itemSets() as $itemSet): ?>
                                <dd class="value"><?php echo $itemSet->link($itemSet->displayTitle()); ?></dd>
                                <?php endforeach; ?>
                            </div>
                        </dl>
                    <?php endif; ?>
                    <?php if($item->media()): ?>
                        <dl class="media-list">
                            <div class="property">
                                <dt><?php echo $translate('Media'); ?></dt>
                                <?php foreach ($item->media() as $media): ?>
                                <dd class="value <?php echo is_array($decoration) && in_array('media', $decoration) ? 'decoration decoration--thumbnail' : ''; ?>"><?php echo $media->linkPretty('square', $media->displayTitle(), ['class' => 'media resource']); ?></dd>
                                <?php endforeach; ?>
                            </div>
                        </dl>
                    <?php endif; ?>
                </div>

            </div>
        </div>

    <?php endforeach; ?>
</div>
