<?php
$item = $marker->item();
$media = $marker->media();
?>
<?php if ($media) : ?>
    <?php echo $this->thumbnail($media, 'medium'); ?>
<?php endif; ?>
<div class="mapping-marker-popup-text">
    <?php if ($marker->label()) : ?>
        <h3 class="mapping-marker-popup-heading"><?php echo $this->escapeHtml($marker->label()); ?></h3>
    <?php endif; ?>
    <div>
        <?php echo sprintf($this->translate('Item: %s'), $item->link($item->displayTitle(), null, ['target' => '_blank'])); ?>
    </div>
    <?php if ($media) : ?>
        <div>
            <?php echo sprintf($this->translate('Media: %s'), $media->link($media->displayTitle(), null, ['target' => '_blank'])); ?>
        </div>
    <?php endif; ?>
</div>
