<?php
$options = [
    'page' => $this->params()->fromQuery('page', 1),
    'perPage' => 25,
    'resourceProperty' => $this->params()->fromQuery('resource_property'),
];
if ($this->siteSetting('exclude_resources_not_in_site')) {
    $options['siteId'] = $this->currentSite()->id();
}
$subjectValues = $resource->displaySubjectValues($options);
?>
<?php if ($subjectValues): ?>
<div id="resources-linked" class="resources-linked">
    <div class="resources-linked__header">
        <h3 class="resources-linked__heading"><?php echo $this->translate('Linked resources'); ?></h3>
        <button class="resources-linked__expand-collapse-btn">Expand all</button>
    </div>
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>
