<?php
$escape = $this->plugin('escapeHtml');
$resourceMedia = $resource->media();
?>
<?php if ($resourceMedia): ?>
<dl class="media-list">
    <div class="property">
        <dt><?php echo $this->translate('Media'); ?></dt>
        <?php foreach ($resourceMedia as $media): ?>
            <?php
            $altText = $media->altText() ?: $media->displayTitle() ?: '';
            $thumbnail = $this->thumbnail($media, 'square', ['alt' => $altText]);
            $linkContent = sprintf('%s<span class="resource-name">%s</span>',
                $thumbnail,
                $escape($media->displayTitle())
            );
            ?>
            <dd class="value">
                <?php echo $media->linkRaw($linkContent, null, ['class' => 'resource-link']); ?>
            </dd>
        <?php endforeach; ?>
    </div>
</dl>
<?php endif; ?>
