<?php
$escHtml = $this->plugin('escapeHtml');
$escAttr = $this->plugin('escapeHtmlAttr');

$footerLogo      	= $this->themeSetting( 'footer_logo' );
$footerSiteInfo  	= $this->themeSetting( 'footer_site_info' );
$footerMenu      	= $this->themeSetting( 'footer_menu' );
$footerMenuTitle 	= $this->themeSetting('footer_menu_title');
$footerMenuDepth 	= $this->themeSetting('footer_menu_depth');
$footerContentTitle = $this->themeSetting('footer_content_title');
$footerContent   	= $this->themeSetting( 'footer_content' );
$socialNetworks  	= array( 'facebook', 'twitter', 'linkedin', 'instagram', 'youtube', 'mastodon' );

$additional_classes = '';

if ( ! $footerMenu ) {
	$additional_classes .= ' no-menu';
} elseif ( ! $footerLogo && ! $footerSiteInfo && ! $footerContent ) {
	$additional_classes .= ' menu-only';
}

if ( $footerMenu && ( $footerLogo || $footerSiteInfo ) && $footerContent ) {
	$additional_classes .= ' all-columns';

	if ( $footerMenuDepth > 1 ) {
		$additional_classes .= ' menu-depth-2';
	}
}

$hasFooterTopColumns = false;
if ( $footerLogo || $footerSiteInfo || $footerMenu || $footerContent ) {
	$hasFooterTopColumns = true;
}

$hasSocialNetworks = false;
foreach ( $socialNetworks as $social_network ) {
	if ( $this->themeSetting( "{$social_network}_url" ) ) {
		$hasSocialNetworks = true;
		break;
	}
}
?>

<div class="main-footer__top">
    <?php if ( $hasFooterTopColumns ) : ?>
        <div class="main-footer__top-container container <?php echo $additional_classes; ?>">

            <!-- Column 1 -->
            <?php if ( $footerLogo || $footerSiteInfo ) : ?>

                <div class="main-footer__col1">
                    <?php if ( $footerLogo ): ?>
                        <img
                            src="<?php echo $this->themeSettingAssetUrl( 'footer_logo' ); ?>"
                            alt="<?php echo $escHtml( $site->title() ); ?>"
                            style="<?php echo $footerSiteInfo ? 'margin-bottom: 30px;' : ''; ?>" />
                    <?php endif; ?>

                    <div class="footer_site_info">
                        <?php if ( $footerSiteInfo ) : ?>
                            <?php echo $footerSiteInfo; ?>
                        <?php endif; ?>
                    </div>
                </div>
                
            <?php endif; ?>

            <!-- Column 2 -->
            <?php if ( $footerMenu ) : ?>
            
                <div class="main-footer__col2">
                    <?php if ( $footerMenuTitle ) : ?>
                        <h6 class="main-footer__heading"><?php echo $footerMenuTitle; ?></h6>
                    <?php endif; ?>

                    <?php
                        echo $site->publicNav()->menu()->renderMenu(null, [
                            'maxDepth' => $footerMenuDepth - 1
                        ]);
                    ?>
                </div>

            <?php endif; ?>

            <!-- Column 3 -->
            <?php if ( $footerContent ) : ?>

                <div class="main-footer__col3">
                    <?php if ( $footerContentTitle ) : ?>
                        <h6 class="main-footer__heading"><?php echo $footerContentTitle; ?></h6>
                    <?php endif; ?>

                    <?php if ( $footerContent ) : ?>
                        <?php echo $footerContent; ?>
                    <?php endif; ?>
                </div>

            <?php endif; ?>

        </div>
    <?php endif; ?>

    <!-- Social Networks -->
    <?php if ($hasSocialNetworks) : ?>
        <div class="main-footer__social-network container">
            <?php foreach ( $socialNetworks as $social_network ) : ?>
                <?php if ( $social_network_url = $this->themeSetting( "{$social_network}_url" ) ) : ?>
                    <a href="<?php echo $social_network_url; ?>">
                        <img src="<?php echo $this->assetUrl( "img/{$social_network}.svg" ); ?>"
                            alt="<?php echo $escAttr( $social_network ); ?>">
                    </a>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>
