<?php
$this->headLink()->appendStylesheet($this->assetUrl('node_modules/leaflet/dist/leaflet.css', 'Mapping'));
$this->headLink()->appendStylesheet($this->assetUrl('node_modules/leaflet.markercluster/dist/MarkerCluster.css', 'Mapping'));
$this->headLink()->appendStylesheet($this->assetUrl('node_modules/leaflet.markercluster/dist/MarkerCluster.Default.css', 'Mapping'));
$this->headLink()->appendStylesheet($this->assetUrl('node_modules/leaflet.fullscreen/Control.FullScreen.css', 'Mapping'));

$this->headScript()->appendFile($this->assetUrl('node_modules/leaflet/dist/leaflet.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('node_modules/leaflet-providers/leaflet-providers.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('node_modules/leaflet.fullscreen/Control.FullScreen.js', 'Mapping'));

$this->headScript()->appendFile($this->assetUrl('js/control.fit-bounds.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/mapping-browse.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/advanced-search.js', 'Omeka'));

$this->inlineScript()->appendFile($this->assetUrl('js/advanced-search.js'));

$query['mapping_basemap_provider'] = $query['mapping_basemap_provider'] ?? '';
?>
<?php echo $this->pageTitle($this->translate('Map'), 2); ?>

<div id="mapping-map" style="height:500px; width: 80%; margin:0 auto;"></div>

<form id="advanced-search">
    <?php echo $this->partial('common/advanced-search', ['query' => $query, 'resourceType' => 'item']); ?>
    <div id="page-actions">
        <input type="submit" name="submit" value="<?php echo $this->escapeHtml($this->translate('Search Map')); ?>">
        <input type="reset" value="Reset" name="reset" class="reset-button btn--secondary" />
    </div>
    <input type="hidden" name="mapping_basemap_provider" value="<?php echo $this->escapeHtml($query['mapping_basemap_provider']); ?>">
</form>

<?php foreach ($markers as $marker): ?>
<div class="mapping-marker-popup-content" style="display:none;"
    data-marker-id="<?php echo $this->escapeHtml($marker->id()); ?>"
    data-marker-lat="<?php echo $this->escapeHtml($marker->lat()); ?>"
    data-marker-lng="<?php echo $this->escapeHtml($marker->lng()); ?>"
>
    <?php if ($marker->label()) : ?>
    <h3><?php echo $this->escapeHtml($marker->label()); ?></h3>
    <?php endif; ?>
    <?php if ($marker->media()) : ?>
    <img src="<?php echo $this->escapeHtml($marker->media()->thumbnailUrl('medium')); ?>">
    <div>
        <a href="<?php echo $this->escapeHtml($marker->media()->url()); ?>"><?php echo $this->translate('View media'); ?></a>
    </div>
    <?php endif; ?>
    <div>
        <a href="<?php echo $this->escapeHtml($marker->item()->url()); ?>"><?php echo $this->translate('View item'); ?></a>
    </div>
</div>
<?php endforeach; ?>
