<?php
$siteTitle = $site->title();
$userBar = $this->userBar();
$bannerHeading = $this->themeSetting('banner_heading');
$bannerDescription = $this->themeSetting('banner_description');
$bannerHeightProperty = $bannerHeading || $bannerDescription ? 'min-height' : 'height';
$primaryColor = $this->themeSetting('primary_color') ?? '#d62d6a';
$secondaryColor = $this->themeSetting('secondary_color') ?? '#4D1068';
$accentColor = $this->themeSetting('accent_color') ?? '#0a4f9e';
$complementaryColor = $this->themeSetting('complementary_color') ?? '#F0B247';


$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('https://fonts.googleapis.com/css2?family=Sen:wght@400;500;700;800&display=swap');
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->jsTranslate();
$this->trigger('view.layout');

if ($userBar) {
	$this->htmlElement('body')->appendAttribute('class', 'user-bar');
}
?>

<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
	<head>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headStyle(); ?>
		<?php echo $this->headScript(); ?>

		<style type="text/css" media="screen">
			:root {
				--primary: <?php echo $primaryColor; ?>;
				--primary-dark: <?php echo $this->ShadeColor($primaryColor, -10); ?>;
				--secondary: <?php echo $secondaryColor; ?>;
				--secondary-dark: <?php echo $this->ShadeColor($secondaryColor, -10); ?>;
				--accent: <?php echo $accentColor; ?>;
				--complementary: <?php echo $complementaryColor; ?>;
			}

		</style>
	</head>

	<?php echo $this->htmlElement('body'); ?>
		<a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>

		<?php echo $this->partial('common/header', ['userBar' => $userBar, 'site' => $site]); ?>

		<?php echo $this->partial('common/banner'); ?>

		<div id="main-content" class="container" role="main">
			<?php echo $this->content; ?>
		</div>

		<?php echo $this->partial('common/footer'); ?>
		<?php echo $this->partial('common/menu-drawer'); ?>

		<?php
		echo $this->inlineScript()
			->prependFile($this->assetUrl('js/navigation.js'))
			->prependFile($this->assetUrl('js/script.js'));
		?>
	</body>
</html>
